pelog/force-app/main/default/objects/PELogConfig__c/PELogConfig__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Holds configuration for Platform Events Logging.</description>
    <label>PELogConfig</label>
</CustomObject>

pelog/force-app/main/default/objects/PELogConfig__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <description>Category to log (e.g. Technical or Business)</description>
    <inlineHelpText>Category to log (e.g. Technical or Business)</inlineHelpText>
    <label>Category</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pelog/force-app/main/default/objects/PELogConfig__c/fields/LoggingLevel__c.field-meta.xml
<CustomField>
    <fullName>LoggingLevel__c</fullName>
    <description>One of (lowest to highest):
ERROR
WARN
INFO
DEBUG
FINE
FINER
FINEST
Events of any level equal to or lower than the specified level will be logged</description>
    <inlineHelpText>One of (lowest to highest):
ERROR
WARN
INFO
DEBUG
FINE
FINER
FINEST
Events of any level equal to or lower than the specified level will be logged</inlineHelpText>
    <label>Logging Level</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pelog/force-app/main/default/objects/PELogConfig__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <description>either "All" or Salesforce username of the user whose actions we wish to log</description>
    <inlineHelpText>enter "All" or Salesforce username of the user whose actions we wish to log</inlineHelpText>
    <label>User</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

pelog/force-app/main/default/classes/PELog_TestDataFactory.cls
public with sharing class PELog_TestDataFactory {
    public PELog_TestDataFactory() {

    }

    public static List<PELogConfig__c> createLogConfig (boolean includeCurrentUser) {

        String username = UserInfo.getUserName();

        List<PELogConfig__c> listConfig = new List<PELogConfig__c>();
        listConfig.add(new PELogConfig__c(Name = 'Config1', LoggingLevel__c = 'DEBUG',Category__c = 'Technical',User__c = 'All'));
        listConfig.add(new PELogConfig__c(Name = 'Config2', LoggingLevel__c = 'FINE',Category__c = 'Technical',User__c = 'All'));
        listConfig.add(new PELogConfig__c(Name = 'Config3', LoggingLevel__c = 'FINER',Category__c = 'Technical',User__c = 'Bert@Bert.com'));
        if (includeCurrentUser) {
            listConfig.add(new PELogConfig__c(Name = 'Config4', LoggingLevel__c = 'FINEST',Category__c = 'Technical',User__c = username));
        }
        insert listConfig;
        return listConfig;
    }
}